- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
  tasks:
  - name: Install tmux
    apt: name=tmux
    tags:
    - tmux
  - name: Setup tmux config
    shell: ./setup.sh tmux
    tags:
    - tmux
  - name: Install vim
    apt: name=vim
    tags:
    - vim
  - name: Install vim vundle
    shell: ./setup.sh vim
    tags:
    - vim

