- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
  tasks:
    - name: Install basics
      shell: ./setup.sh vim && ./setup.sh tmux && ./setup.sh python && ./setup.sh node
