name: Aux Nuit

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.8.7']

    steps:
      - uses: actions/checkout@v2

      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test setup.sh
        run: |
          chmod +x setup.sh && ./setup.sh
